### PR TITLE
feat: add gpt4o pricing

### PR DESCRIPTION
**Pull request by hughcrt**

### CODE REVIEW

**Comment by thomasst** [comment]
You should also update GPT4 pricing (e.g. GPT-4-Turbo is $0.01 input and $0.03 output now).

**Comment by hughcrt** [comment]
Hey @thomasst, I think the pricing change for GPT-4 was a while ago.

In March, it was already the same pricing: https://web.archive.org/web/20240306022815/https://openai.com/pricing

We have the up-to-date pricing in the code.

**Comment by thomasst** [comment]
Sorry I must have been looking at the wrong models or version of the file :)

**Comment by hughcrt** [comment]
No problem 🙂

**Pull request merged**
